from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Last investment review agent that spoke"]
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    selected_analysts: Annotated[
        list[str], "Research capabilities selected for this run"
    ]
    analysis_queue: Annotated[
        list[str], "Remaining research capabilities in planned order"
    ]
    completed_analysts: Annotated[
        list[str], "Research capabilities that have finished"
    ]
    current_analyst: Annotated[str, "Current research capability being executed"]
    analysis_plan: Annotated[
        str, "Cross-functional research plan created by the orchestrator"
    ]
    analysis_brief: Annotated[
        str, "Current investment brief shared across the capability stack"
    ]
    analysis_artifacts: Annotated[
        dict[str, dict[str, str]], "Capability-level report artifacts for downstream use"
    ]
    orchestration_journal: Annotated[list[str], "Routing log produced by the orchestrator"]
    decision_dossier: Annotated[
        dict[str, str], "Structured investment dossier accumulated across the workflow"
    ]
    decision_dossier_markdown: Annotated[
        str, "Rendered markdown version of the structured investment dossier"
    ]

    # research step
    market_expectations_report: Annotated[
        str, "Report from the Market Expectations capability"
    ]
    why_now_report: Annotated[str, "Report from the Why Now capability"]
    catalyst_path_report: Annotated[str, "Report from the Catalyst Path capability"]
    business_truth_report: Annotated[str, "Report from the Business Truth capability"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Memo generated by the Investment Director"]

    trader_investment_plan: Annotated[str, "Execution blueprint generated by the Execution Engine"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final capital allocation decision"]
